#  ATTENTION:
#   This file needs to be under version control.
#   If you have to include sensitive information in it then just copy and rename it.
services:
  db:
    image: mariadb:10.4
    container_name: SLED_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 54321
      MYSQL_DATABASE: strong_lenses_database
      MYSQL_USER: sled_root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p54321", "-e", "SELECT 1"]
      timeout: 5s
      retries: 10
    volumes:
      - data:/var/lib/mysql

      
  redis:
    image: redis:8.0.2
    container_name: SLED_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

      
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: SLED_server
    command: sh -c "cd SLED_api/ && cp run_dev_server/settings_development.py mysite/settings.py && python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    #restart: always
    volumes:
      - <SLED_api>:/SLED/SLED_api
      - <init_SLED>/files:/files
      - <init_SLED>/static:/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

        
  celery:
    build:
      context: .
    container_name: SLED_celery
    command: sh -c "pwd && ls && cd SLED_api/ && pwd && celery -A mysite worker --beat -l info"
    volumes:
      - <SLED_api>:/SLED/SLED_api
      - <init_SLED>/files:/files
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - backend
      - redis

        
volumes:
  data:
